### ISSUE TITLE
方針

### ISSUE THREAD

**Issue by s-osa** [SatoTatsuhiro/dankaiGP#1]
# たった1つのたいせつなこと
1. 計測する
2. 遅い箇所を早くする
3. 計測する
   - 速くなった場合
     1. 1へ戻る
   - 速くならなかった場合
     1. 戻す
     2. 1へ戻る

無限ループって怖くね？
# 構成要素
## 主なもの
- Nginx
- Unicorn
- Rails/Ruby
- MySQL
## その他
- memcached
- Redis
- Varnish
- Puma, Raptor
# はじめにやること
- [x] ログイン&SSH設定
- [x] サイトを触ってみる
- [x] 本番サーバにgit入れて、触っていくファイルをバージョン管理下に置く
# やっていく
## DBクエリ系

mysqldumpslowが最大の武器（100ms→10ms）
- [x] index貼る
- [ ] テーブル定義見直す
- [ ] でかいデータを別テーブルに切り出す（optional）
- [ ] N+1
  - eager loading
- [ ] OR削る
- [ ] SELECTするカラムを絞る
## App系

Rails用プロファイラが最大の武器（？）
Nginx用プロファイラで重いエンドポイントを特定するものアリ？
- [ ] セッションキャッシュ（？）を適切に使う
- [ ] DB設定を良い感じにする
## ミドルウェアの設定
- [x] MySQLのバッファ
  - innodb_buffer_pool_size
- [x] Unicornのworker数
- [x] Nginxのworker数
- [x] Nginx - UnicornをUnix Domain Socketで繋ぐ
- [x] Nginxから静的ファイルを返す
## cache戦略
- [ ] memcached
- [ ] Redis
- [ ] Varnish
## やるかどうかビミョー/無理っぽい
- [ ] GC止める
- [ ] TCP dump
- [ ] kernelチューニング
## さいごに
- [ ] ログを切る

**Comment by nano041214** [comment]
[mysqld]
slow_query_log = ON
slow_query_log_file = /path/to/mysql-slow.log
long_query_time = 0.1
